server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Páginas
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache longo para assets estáticos (css/js/imagens/fontes)
    location ~* \.(?:css|js|png|jpe?g|gif|svg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    # Compressão
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types text/css application/javascript image/svg+xml application/json;
}
